version: '3.7'

services:
  dev:
    container_name: app-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app-frontend'
      - '/app-frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true