version: '3.7'

volumes:
  node_modules:
services:
  dev:
    container_name: app-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app-frontend'
      - 'node_modules:/app-frontend/node_modules'
    ports:
      - 3000:3000
      - 6006:6006
    environment:
      - CHOKIDAR_USEPOLLING=true